sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: xXl3GcRnxUQcJfSpPdNOvctHX4qKHCeU3V7JEmVAhzw39KKuiuEbWZ84gOrE1etTGZ90fKE/ydXa384FFVEukRzaSEizrQO5EbG1o77pfxC0gkESdUCqk3X+chzlAWnMhiJukYo3IbiIcB0pVPVSKiA1DfwDPZQQkdCxuTQTCxJ2OGOQ6KMbvm7yXbJhGj6EnXJXFfXG9v/DE/11uYBAx5lZuWi78W6olZyG+Utf50L23oOckmXSokCHlMSMRwB6mfVUaQr+uIsENvvF+IQgrEsw7YfrNWSeb7XrrMp+Eg68PstPesWYQ3H2hRzVz6C+Ck9b6SdIJWPzp/09oMlMsKr6ltvpbluTEgnoBbeZzhsX7mROt68z/wZdUG0WzAqR2910TMah8GgN/BA7VTVPvErE7zDUFn33191mLvudLeUz/omeAqrBvEfEHwU/M8njSctaeJ0SNnv9hyQ2AXBLUExONuztBZvv1NnDnyEpBcWULjKovCMo5ldVOKO1w7x2t1waSx7cnadlHKKRQzGogSwDKo/cdSUSBmvOhD71PEIp1x1QJwBQA2F/cJqelSFN0YXaHr86G3tDlDQF62sJL8byPLzTNXj3FAkTZqwQWpznwxjjFDHdPtD5ZIlrTaD+GwVT47gMAasLHU5l/pv8BxazOyr6aG++iMltjwM3KnE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Machine_3304
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy